#!/usr/bin/env node

var sqlite = require( 'sqlite' );
var options = require( 'nomnom' )
	.opts( {
		add: {
			abbr: 'a',
			help: 'Add mirror'
		}
	}).parseArgs();

function list() {
}

function add() {
}

function remove() {
}
